name: Deploy
on:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run client tests
          run: |
            cd client                                                                                                                                                                                             
            npm install                                                                                                                                                                                         
            npm test -- --watchAll=false

    build-and-push:
      needs: test  # запускаецца толькі пасля паспяховых тэстаў
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push client
          uses: docker/build-push-action@v5
          with:
            context: ./client
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/complex-client:latest

        - name: Build and push server
          uses: docker/build-push-action@v5
          with:
            context: ./server
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/complex-server:latest

        - name: Build and push worker
          uses: docker/build-push-action@v5
          with:
            context: ./worker
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/complex-worker:latest

        - name: Build and push nginx
          uses: docker/build-push-action@v5
          with:
            context: ./nginx
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/complex-nginx:latest
